---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse
  namespace: synapse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
