apiVersion: v1
kind: Service
metadata:
  labels:
    app: synapse
  name: synapse
  namespace: synapse
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: synapse
  selector:
    app: synapse
