---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  timeout: 20m
  chart:
    spec:
      chart: traefik
      version: "10.19.4"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  values:
    ingressClass:
      enabled: true
      isDefaultClass: true
    logs:
      access:
        enabled: false
      general:
        level: INFO
    persistence:
      enabled: true
      name: traefik-data
      accessMode: ReadWriteOnce
      size: 128Mi
      path: /data
    ports:
      web:
        redirectTo: websecure
    service:
      spec:
        externalTrafficPolicy: Local
  valuesFrom:
    - kind: Secret
      name: traefik-values-secret
      valuesKey: values.yaml
