apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: earnings-bot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: earnings-bot
    spec:
      containers:
        - image: docker.io/library/postgres:13
          name: postgres
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
              volumeMounts:
                - mountPath: /var/lib/postgresql/data
                  name: storage
          volumes:
            - name: storage
              persistentVolumeClaim:
                claimName: postgres
