---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trades-pvc
  namespace: thetagang
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trends-pvc
  namespace: thetagang
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
