apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: thetagang-notifications-secret
    namespace: thetagang
data:
    WEBHOOK_URL_EARNINGS: ENC[AES256_GCM,data:fdjSJqoU9Ofd4NitazpEFnwr6FjaL6R9neT6qZmvIbOTDiKWd0/bCT1pRcz9RpmOWs7EILA9AzYc0UflwnXMasmqQz1nu7fQEY3nrUQSOjKr8D6LgSdxNyLxb9fL28tckZ2QaSoSV7sgaW4UVGm/PfTJGAhX7Yf/BuMWB+1RIVs9hmmcni8ygf7r1/zadqzUPFHjaqlUPjzqPglaOL1wnA==,iv:BsT/AKpmHn4cPrfVik+QnZYk4c/o079u3vn0OmkIKb4=,tag:As+JBCIyMt/xAa2Aa9L2ig==,type:str]
    WEBHOOK_URL_TRADES: ENC[AES256_GCM,data:ak0deb91QFubd0Avhw/O3HQ1wNmR4iejrIboSTpZbWmZgn3i5gvpKUbCGI+mDnyqX3SrrT+rNHYl15reof8g8iDtsijMB7p3e+A76R6uCx6gIgLqxjPJW+LC2UqfusMPloQV568T/XUIks689AxoKR4KBwyjhKRsJcjdXOPDOQ12f/8hWfkS423ISlZMwuA5zhcGbeht1oZCTb6zgpHuhw==,iv:n2UFFNU9QfJHfFqSHTtGcZ1Cjo9h6EqFHKYO7Ip8AQ4=,tag:e/p4NjtPR9v0kMvSTmgRFw==,type:str]
    WEBHOOK_URL_TRENDS: ENC[AES256_GCM,data:SPfx6hMnQpfTeptE8PkZHIu+dH2o+6Ailsl2+slAs8s3HXFNJP7CMHaxfSkMubze0FlpQVGbxUQaJv8kyIxYc+CJdsJZMOba2HnO6iOtY6X9S9FflmvMJzDxAxo61EdFDfAGxeDoH5MAjBXCx4l5YDw9ekeBKkIJbadzFsLglmIUsLXy/jLWi2lI4PyQSfouIWpSOsXd9QaKKuzZb8qWPg==,iv:XI+HRC+MvHo0O33K+bo55nlwFSk8BeKdvyrbHkDAHz0=,tag:JIos8rm3o+ZOaT9Gfbv65w==,type:str]
    #ENC[AES256_GCM,data:940Ja2iFMaSmG+n2TIvYZo1zoqa8gpwxdkWFcrCn6v8tKZ+kjv5z0lWF/IRtqMEVZpyD5qbwuoZt3D8OgWuT5FyVDCxbYRwqQxJ42iTD9liw2vpfN2MZ1fu7+LiWe6zEgrPTIkPpj4TERZbZBgdV/NCQ3dradY6ah8VNvypeFrnnzwy+/JncmU35CkJNBNQ=,iv:Jk/Bw+rtbX7XDQM4xh7BlwaXcbPIXd7WN1epM1zCQu8=,tag:lkq5uXVNqS6SUJ99SskA6w==,type:comment]
    #ENC[AES256_GCM,data:cu2rcRX9L6ZDmmM9+xjSx3/vlBHWKfNzZNUrC8xh8uD/Dy5FhkfHCMh2tSCEUZhWzsp8XCx4T9SjXDuhm0/pz8hOLUuTYAU89QdWnWq+xN33RZI3I/JbtEf7fRPl92EYGJDf2XHvVLr3xTkHLyx9IRSLc2xzlFvjTdIaaK4uA/uGpiGF8MvMghxLnhVEO2ytKtxRKoGjetlsWKqhI0lScWxQ87s1iYUELtBG,iv:WE43wTt0egl/Pqha6e2wRtnCrss9p0Cp/bAuwsg/y7M=,tag:hRENs78QE4smyPYdj6Z19A==,type:comment]
    #ENC[AES256_GCM,data:um8qeor0xoMqkkYlx491W2AuPbC+8Q2gbMRBtmDaqqJSy6tq1b4VMQhDrriI+orlBjJM4v0GYJwg9NazDLbidqpZS4L8y81uE8khTYWoMXhAol2oH9Q/OF/QM6TuX96BU48U6ODETF5V3h1qOpdjjmS9P8ALyMSoUoSlcHHo19NBUzPCGkezgqJlycFG5kEnNY7GASasT2WYkFXc2edy1kwqLa3cQ/BrHRf5,iv:e49fbl3ntNm2cvm6qyDTSkxG96GX6pnYKXoamvAbAwI=,tag:B3RuYw7L0HO8atp1zo7eOA==,type:comment]
    TWITTER_CONSUMER_KEY: ENC[AES256_GCM,data:COVzI2mXD+KUccmdfj/WsjiRVQUf+1/LTbI370vvI/PEYpjJ,iv:HM/xXG8RU3YUVeHDZsOHopjMeWrLN+beWBNX1J2vD08=,tag:bqpCfIMgCNkEW0dG8yntTg==,type:str]
    TWITTER_CONSUMER_SECRET: ENC[AES256_GCM,data:7wzjj/QhwonOD3ejY8kRAw1ynINxGH4GIayJh5VSNY+KX8mvA/RyfsM4xVf5OwFSZpmuZvye/SOA+uIdkfrTlXiKIOU=,iv:qCDzemPy54NNX7+ZfNz6Sgw9eDr3qy5Kia/j/vm1+00=,tag:CiCvGwp0IAWkz6eryBIfSg==,type:str]
    TWITTER_ACCESS_TOKEN: ENC[AES256_GCM,data:yW5F9IdItvnZdZaq3igPMTJwcIUPvXAhY70y/t+NGNtgs3sx51vmfbHSjnQBXIAtaEslHnXWEsV08cBDsDPojTG9xhg=,iv:fLS3/3xmfhetsupXcBTJrsizDDotov4ARGg9YGhoegY=,tag:ixOHCV7hW/QXRWsHo1V2jg==,type:str]
    TWITTER_ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:K+j2Jr1ToCaMHQ6B7e5q9v5EJ+WnioyRGgwvKRmadjErXB7vWhuvzkM3VMmf5dsOEIKXfIhZuM9DbcOc,iv:/1JvjxvpruNdO//rGx8h4rnUAttYuZJUjJ6fUkMHYRQ=,tag:d4e8QCIbBTLQQuSIXHDAAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtmmjw35qswy9zaah33js64y94v6lrfnjlxx264s8w56s6u47e5qdds752
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscFVuYzRBaG16YnFMWlVU
            VVRyLzdtT3U1Wkx0Y1VXK1dyQVlhbEpLaXdZCnU1WkhlOE81WkxHZ3AvcWx3dGxh
            S0NEWGI2WFNvUE1zeE9TVTB6bWdVVkUKLS0tIDNJWFNPM20yRUhobXFlemZTTnZ2
            a3FpQk9Vay83VE5DdDB6UHRxV1F3Z28KHE7EIc9qaUrXCBe/WL9nhlVJ6Dbg5xNF
            c8cYBLYmn5f78p5xlb6PMWhWjGdeQwoCr3b25JWxCgsUILGjUB1mAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-13T12:54:41Z"
    mac: ENC[AES256_GCM,data:g/cPGKQLoUYfLimjdmKa/iZsEo+GMDeD+RgJztsriS5ITqZIT/47JwkKzRY5aSxHMLv3N+qHj2dTCuN2l37PulcsTVfiPeGxe1U8TPsFZ2lsLdTX5fjWc3p8AVrbjU0eBtYwTbGbj0uvJqWjdqiZNGPSGscRZHoayPFP2SE03Yo=,iv:0e7BE03v+hGhgbV1HuOCwdn5lVCfWE9SNKSj7QE7aX8=,tag:lFz8ShP6rBqfivH8WvCssw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
