apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:gDWwDlsQtfniS6j3o/8qTbYAW7oj5Qva6nQ9gKDYr7/1SATTVERlx96UnLkWLIuSaW+8OWrFa/HCokAXBdl8ANtT14aof4akaJGRwbuqGHKmSv8wJ7RC+bHqRrIw+9eDnhRzf/2UDn2/XdXGEw+MHE3GqIZkQpmpk4Y0Xh0thsEEHSHVUBuqLEDDznLXElnahiOfxF2b6avYKPP7N5Kkvpi0YKYXtUX9Gi0fFd3v4AFfQTdcHQM14Etk4rfe+dqYGdJby+pFiXPsgdLCatLIoTAf9jogmsO39uKbCcx+YZzxGujY7Ti8+Ktyz3TDf5U7AwwZ4ByugHMQ2l3Ex/8OPJ2DVNd3ODQ+h+f99eR+NI4HEuUguJpMNddN6V9bdjdEKcJCFRKFoxVjJnhozjXPkwE/toyPkhRsXZ1pl1XH8np1swZ0vtpSPXgnFU2yVCjHCotV8ClXMoei40uoX50Ug5BKeOHs8v4sJ/5QVrGb16hPYUyRdQlr1YfezkJAnw8KgDMmhp7ICL8sR9/gaz0cQLGsTA/jqZoskZ5DXjAyrxz8BNW4qxYhl0kwE+G8Xi+9hw2Fac78rMbmU4C91vdx8VJ2Tu3tk3CRn3e6edapcJnQB+FH9Q8SZyiedM184AvBFkpy8L5A3U5UPM41A08YIjl2ysminkfl0AhbkWTIKL2I9Os8w0xHuaT3/fcr6yAVh/+V0WSEGTm25cO+EMPKhk5FPNygL2fxlI8YQJPZZbLipa2uSX0GLkJgVuCvxoDPymfZmMshQ4Yxzdwcnrq/KTJgwIdWqxw8HsaLbFIs17Wa5AslIUVRF4ndTtNPrbEoTSlFl9GC0MhTeZFHBiSTH5QGtt3sJr8TDpShV9SRILrZ8xIqLC/DHJ0Rr6bcPN6nIoWF2KBdFfbfkzePs8X47CjhJNJezFAnLuGeb7iV6QmRHK05bip7LEmdtjh9T1v4TnkO76Ro3C2Rz1ik/3KcrnWxMBUieUJhhQ0geE+81XrPsfRnf0TH3w==,iv:9NnWO4S5os14Ntlyug+lmoF7ylRmUyN+YuNTd+25A7Q=,tag:JxENB2+8mdp7x+STy0xxbQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: traefik-values-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtmmjw35qswy9zaah33js64y94v6lrfnjlxx264s8w56s6u47e5qdds752
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYmZQUDhlQzFxSktTeEdM
              d0Z6T1lBOG8rRHN0OG9MWG9xcGRON0tyd0hNCmNGN1dqdDN5dVBMcnVIMzlUc25H
              OTMwZzFNbWplYVFFUUxTTHZleG5WU2cKLS0tIDRBSm5MWTNkczIzL3hmVEd2NERP
              c3Z1cXcvdFBwdDJQaU9NMlBQeGwrUVkKYl+gyXTc+FlWcpBilRpF+DaBhonBHRHv
              svTNScynN6TBGVKiMTXIbOkQvCC7JUmc9A/h0JRe66Xw9I9RnICTaA==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-13T20:35:56Z"
    mac: ENC[AES256_GCM,data:Yvc5Q+oqXPPyRzKCP49pyAvxIbFvAC13yIbUEJeHHmPAGDFJwqq0/rWsWbpkEz+AoSe28APHeYopBg7sbLNf6+2TePzILbiKZ4F01q6lo9u+Xh2Pm1zSBveyaygBFgjHqCE7GOT2HOwwVQa1uSPc74gX6Ooc/ZRqq6Rv+or7tds=,iv:hZ11R64wLHiJsge0uDo44rT8CwB+cx13I1DGGL8W15c=,tag:J7rXortOfWvvhg3QhqzI4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
