apiVersion: v1
data:
  values.yaml: ENC[AES256_GCM,data:7TaexP47nQdFXiEBjk9t4KsSEK38Q4PgRIneEiQQ8r3UiYnXh1OsB+xwCJxfUrLQcyll1h+BV/VhRM0khbq4NS3QZ8ZqqR3mZIaSqhN/ln0pOrdwHZDDktrzEykmI8WWeUcbuKvzuMcYJI6BTKabdEUH1bsWY+HKjRBtODavFBegZx7KEyVGvbe5VQQ/jD/v9be/LHCLhJmOL/9PmqxAIxDQDWVKsey9X/YcJhZB8uypwWjd0RjFScSMPZAw5CpaoxMAki6pClRvwDZfsXlLPlfNfMwiptK6uFuyjgwhw5Ntn78YE0E+SNO0Kbz0fiwmtZDqE+spQhdXjq/RXSYgvYFDTfiKZ6Ro89dk7fvXG0IxfjYuu1Mn9Glc8g33pd3iPFlTvWZ8ZNP8JDsypCroSXR00VpPJrHMhq1nLx40Yk50TRUjp6hvRGoPQ2FEkaVNwqww2S1qrZXir+Or+MAa+G46GIs1f2Gq7eMTDHH8HZ8poH6vAqq5sncGMDxG8w6LHYEGFQjrtt1q2uZb3t+3WtDtoTi4cwkCaiYLoSYdh7jPBoA4nF3rIOfJ1GhK4PZIs++3D64r5xSBd3GJ1U3nVlEeURNXofgU0N2xBu4CVvv7KAeRl/TlnE6DdYS9TmAEnOrKqAQuQYkawCzcKNsjiWeVCrnlK/1ElGqCceHj+XQOyC6J52j0pD+v17vSuLAXbEIiC5Ry2Bkb711JLEVJXbX6Y2+b7y+NDTIAh91PuM/YNitFCqosX9s/7U6CffRz/p3geORukFZOhf6VeGOwky4+TcOB3Cq0ctrtTiN4kGRcpJUR3zyhlY44lgd4neJfu1zbtyvBt6h5fs9NaGB+Z+SNTd4pPmRVKlMiAqtZcvyow56YxrIsNnzlqfIPjRXQyMKGJokrAiIYaesQEhfkZPe37crcPIHYDl/ghlMtXvFM2P1oteiD1pQEg5M3P4lv90yL6pxWNEpJN5ElyVn8jOxO+IBdMOFxmgKVwgOKgzpzqqhOIKSIYooHj1n4sQJaRnig60ODp7+eUcqDwmRuFSZ7Ipk6Hj/cvBOiDT/Z36e+sjNh+oDSYgxs3t+AosSci8Jq1zXRu+VYnlbCEAdYus8NP3TCSEDVuu3kT/NbncqWtJa/HKcDIBair0RybCH0p6ats1izWOcHOtb4CNHeZA==,iv:X63jJ4PK4KdauUGbZMtHXFKDG+JACWlw8qgI46huYw0=,tag:sUOALfyRY2xZKGhdjlWAwg==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: traefik-values-secrets
  namespace: traefik
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rtmmjw35qswy9zaah33js64y94v6lrfnjlxx264s8w56s6u47e5qdds752
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTE02NUVzQTFVK1R0R3Bl
        M1Z1ZXFDYW5iRDJ2bjM3SlBNOXhQS0JTTjB3ClN4VVhmaVE2MGFlb1VMTTNxS2Yv
        bEJ2YytubVRqL0w2NUZLNDM4dSt2Q2MKLS0tIHNDVUdoMlM1bXFmc3RlWXFZL0Jr
        VnlFSlh5aVJkL200eElIdlBVYUNvTFUKdsCY5uurSA9+YNhVRskILR0rnBf02iVq
        RR5155zGRd56yVY+q9awNWNm5brdxR5OSBQVLEwGq5Q93eRoBFYUGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2022-04-13T21:15:56Z"
  mac: ENC[AES256_GCM,data:1AI52Uh4WQp7qFwWUOlsDfjSeoDbWNxfNmdSqAEBP6V8vrh3kNKYTVUMWJP3NP+4T+dhxuiZJ+n4lueBPheSThfQeii/V8vmJ6MIncMTcCLVsECxBkIRj5WF0Tjy2weEKfC3EkqazTMirVXzMp9utEmsFMsr+IkHo4UQtr1P6A4=,iv:Rjb1KfNfiMnNgY+L4d3ou+0xYo+TlQ9UjH7pnjwXMSk=,tag:pXKeHhRrM5yh+l6rsfscKA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.2
