apiVersion: batch/v1
kind: CronJob
metadata:
  name: trades-bot
  namespace: thetagang
spec:
  jobTemplate:
    metadata:
      name: trades-bot
    spec:
      template:
        metadata:
          labels:
            job: trades_bot
        spec:
          containers:
            - image: ghcr.io/major/thetagang-notifications:v1.0.9
              name: trades-bot
              command:
                - /app/run_trades
              envFrom:
                - configMapRef:
                    name: thetagang-config
                - secretRef:
                    name: thetagang-secret
              volumeMounts:
                - mountPath: /data
                  name: storage
          restartPolicy: Never
          volumes:
            - name: storage
              persistentVolumeClaim:
                claimName: trades-bot
  concurrencyPolicy: "Replace"
  suspend: false
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
